name: quiver_log
version: 2.0.0-nullsafety.0
author: Adam Bender <bendera@google.com>
description: A logging utility for Dart, part of the Quiver utilities. Provides an easy to use Appender/Formatter model for Dart logging.
homepage: https://github.com/google/quiver-log
environment:
  sdk: '>=2.12.0-0 <3.0.0'
documentation: http://google.github.io/quiver-log/
dependencies:
  intl: ^0.17.0-nullsafety.2
  logging: ^1.0.0-nullsafety.0
dev_dependencies:
  test: ^1.16.0-nullsafety.17
  mockito: ^4.1.3
  pedantic: ^1.4.0